import os
import pytz

TIMEZONE = pytz.timezone('Asia/Tokyo')

LIST_ID = os.environ['TWEETTRASH_LIST_ID']
CONSUMER_KEY = os.environ['TWEETTRASH_CONSUMER_KEY']
CONSUMER_SECRET = os.environ['TWEETTRASH_CONSUMER_SECRET']
ACCESS_TOKEN_KEY = os.environ['TWEETTRASH_ACCESS_TOKEN_KEY']
ACCESS_TOKEN_SECRET = os.environ['TWEETTRASH_ACCESS_TOKEN_SECRET']
DATETIME_FORMAT = '%a %b %d %H:%M:%S %z %Y'
OUTPUT_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S %z'

DB_LOCATION = os.environ['TWEETTRASH_DB_LOCATION']
